### ISSUE TITLE
Unable to load extension due to error

### ISSUE THREAD

**Issue by KieranCarden** [utopia-rise/godot-2.5D-isometric-map-editor#26]
**Describe the bug**
When trying to activate plugin/extension, an error occurs that prevents the extension from loading:
`Unable to load addon script from path: 'res://addons/IsometricMap/isometric_map_plugin.gd' There seems to be an error in the code, please check the syntax.`

Additional errors seen in scripts (see screenshots)

**To Reproduce**
1. Download latest release from release section
2. Follow installation guide here - https://github.com/utopia-rise/godot-2.5D-isometric-map-editor/blob/master/.README/INSTALL.md
3. Go to enable extension in Godot

**Expected behavior**
Extension/plugin should load correctly and be usable

**Screenshots**
Loading extension
<img width="1062" alt="Screen Shot 2020-06-08 at 8 28 28 PM" src="https://user-images.githubusercontent.com/4044137/84096539-d0822e80-a9c7-11ea-8963-bf51896abac5.png">
isometric_map_plugin.gd
<img width="1278" alt="Screen Shot 2020-06-08 at 8 30 43 PM" src="https://user-images.githubusercontent.com/4044137/84096552-d415b580-a9c7-11ea-914e-d697b3d64e24.png">
isometric_map_inspector.gd
<img width="1272" alt="Screen Shot 2020-06-08 at 8 38 26 PM" src="https://user-images.githubusercontent.com/4044137/84096620-fe677300-a9c7-11ea-8c74-335c52c70d43.png">

**Desktop:**
 - OS: OS X 10.13.3
 - Browser: N/A
 - Version 3.2.1.stable.official

**Comment by piiertho** [comment]
That's weird. I don't have this error on my side.
It looks like it has problems with the GDNative registered type inheritance.
I'll try to reproduce on my lunch time.

In the mean time can you provide me some more informations:
- Did you registered IsoServer singleton ? (Should not be related, but I ask in case)
- Do you have any error when opening project, like library loading error or whatever. (If yes please provide full log)
- Can you copy the global_script_classes section of your `project.godot` ? It should looks like this:
```
_global_script_classes=[ {
"base": "Node",
"class": "EditionHandler",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/handlers/edition_handler.gd"
}, {
"base": "Tree",
"class": "FileTree",
"language": "GDScript",
"path": "res://addons/IsometricMap/widget/files_tree.gd"
}, {
"base": "Node2D",
"class": "GridCursor",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/grid_cursor.gd"
}, {
"base": "Resource",
"class": "IsoPreviewGenerator",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/iso_preview_generator.gd"
}, {
"base": "Panel",
"class": "IsometricAssetSelector",
"language": "GDScript",
"path": "res://addons/IsometricMap/widget/isometric_asset_selector.gd"
}, {
"base": "Node2D",
"class": "IsometricMap",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricMap.gdns"
}, {
"base": "EditorInspectorPlugin",
"class": "IsometricMapInspector",
"language": "GDScript",
"path": "res://addons/IsometricMap/isometric_map_inspector.gd"
}, {
"base": "Node2D",
"class": "IsometricPlaceholder",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricPlaceholder.gdns"
}, {
"base": "Node2D",
"class": "IsometricPositionable",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricPositionable.gdns"
}, {
"base": "Node",
"class": "IsometricServer",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/IsometricServer.gdns"
}, {
"base": "Node2D",
"class": "IsometricTile",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricTile.gdns"
...
```

**Comment by piiertho** [comment]
Ok, I think I got what happened.
On first use on OSX, it does not open dynamic library because it is not signed by an apple developper:
![image](https://user-images.githubusercontent.com/48322356/84142384-fa356700-aa54-11ea-86e7-7994fb132d79.png)
Here click on cancel.
Then go in your security and confidentiality settings and authorize the library:
![image](https://user-images.githubusercontent.com/48322356/84142478-23ee8e00-aa55-11ea-8e9e-53f1328cee5e.png)
Then open project again, it will tell you that apple cannot verify the developer.
Click on open:
![image](https://user-images.githubusercontent.com/48322356/84142560-48e30100-aa55-11ea-81ea-48c5ef39b1a3.png)
Then you should be able to load plugin.
Sorry about that... Apple things ...

**Comment by KieranCarden** [comment]
Thanks for the response! Unfortunately I'm still not able to load the extension. I've tried both using the release version and cloning the entire repo; both result in the same errors.

- I do have the IsoServer singleton loaded and enabled. I have tried disabling and re-enabling as well just to be thorough.

- When I run the project, the following logs output:
```
**ERROR**: Can't open dynamic library: /Applications/Godot.app/Contents/MacOS/../Frameworks/libGodotIsoMapEditor.osx.release.64.dylib, error: dlopen(/Applications/Godot.app/Contents/MacOS/../Frameworks/libGodotIsoMapEditor.osx.release.64.dylib, 2): image not found.
   At: platform/osx/os_osx.mm:1804:open_dynamic_library() - Condition "!p_library_handle" is true. Returned: ERR_CANT_OPEN
**ERROR**: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483:get_symbol() - No valid library handle, can't get symbol from GDNative object
**ERROR**: No nativescript_init in "res://addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib" found
   At: modules/gdnative/nativescript/nativescript.cpp:1506:init_library() - No nativescript_init in "res://addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib" found
**ERROR**: No valid library handle, can't get symbol from GDNative object
   At: modules/gdnative/gdnative.cpp:483:get_symbol() - No valid library handle, can't get symbol from GDNative object
**ERROR**: No valid library handle, can't terminate GDNative object
   At: modules/gdnative/gdnative.cpp:388:terminate() - No valid library handle, can't terminate GDNative object
```

- The following is my global_script_classes:
```
_global_script_classes=[ {
"base": "Node",
"class": "EditionHandler",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/handlers/edition_handler.gd"
}, {
"base": "Tree",
"class": "FileTree",
"language": "GDScript",
"path": "res://addons/IsometricMap/widget/files_tree.gd"
}, {
"base": "Node2D",
"class": "GridCursor",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/grid_cursor.gd"
}, {
"base": "Resource",
"class": "IsoPreviewGenerator",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/iso_preview_generator.gd"
}, {
"base": "Panel",
"class": "IsometricAssetSelector",
"language": "GDScript",
"path": "res://addons/IsometricMap/widget/isometric_asset_selector.gd"
}, {
"base": "",
"class": "IsometricMap",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricMap.gdns"
}, {
"base": "EditorInspectorPlugin",
"class": "IsometricMapInspector",
"language": "GDScript",
"path": "res://addons/IsometricMap/isometric_map_inspector.gd"
}, {
"base": "",
"class": "IsometricPlaceholder",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricPlaceholder.gdns"
}, {
"base": "",
"class": "IsometricPositionable",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricPositionable.gdns"
}, {
"base": "",
"class": "IsometricServer",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/IsometricServer.gdns"
}, {
"base": "",
"class": "IsometricTile",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/IsometricTile.gdns"
}, {
"base": "EditionHandler",
"class": "MapEditionHandler",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/handlers/map_edition_handler.gd"
}, {
"base": "LineEdit",
"class": "NumericLineEdit",
"language": "GDScript",
"path": "res://addons/IsometricMap/widget/numeric_line_edit.gd"
}, {
"base": "",
"class": "PlaceholderType",
"language": "NativeScript",
"path": "res://addons/IsometricMap/GdnsScripts/positionable/PlaceholderType.gdns"
}, {
"base": "Node2D",
"class": "StairSelector",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/stair_selector.gd"
}, {
"base": "EditionHandler",
"class": "TileEditionHandler",
"language": "GDScript",
"path": "res://addons/IsometricMap/Scripts/handlers/tile_edition_handler.gd"
} ]
```

- I never get the prompt to allow the `dylib` from just opening the project, however by trying to open it directly (go to file in the addons dir, double click to open) I do get that prompt, which I then did allow. No difference was made however as I still am unable to activate the plugin and the above errors still occur when running the project.

- When I open the repo project (before running project), the following error is in Output:
`modules/gdnative/nativescript/nativescript.cpp:92 - Condition "!script_data" is true.`

- Starting a new project with just the addon release seems to give the best starting point though:
```
 Can't open dynamic library: /Users/[user]/test/addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib, error: dlopen(/Users/[user]/test/addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/[user]/test/addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/[user]/test/addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib.
 modules/gdnative/gdnative.cpp:483 - No valid library handle, can't get symbol from GDNative object
 modules/gdnative/nativescript/nativescript.cpp:1506 - No nativescript_init in "res://addons/IsometricMap/libs/osx/libGodotIsoMapEditor.osx.release.64.dylib" found
 modules/gdnative/nativescript/nativescript.cpp:92 - Condition "!script_data" is true.
```
Specifically the `(which was built for Mac OS X 10.15)` line, stuck out to me since I'm running 10.13.3. Though this does go away when I allow the library through the security prompt, so I'm not sure if it actually has any significance.

Apple being apple :/ Please let me know if there's anything else you need from me. I would love to help do what I can to solve this.

**Comment by piiertho** [comment]
I think it would be easier to debug with voice and screenshare.
Can you add me on discord ? you can find me on godot kotlin discord: https://discord.gg/qSU2EQs

**Comment by KieranCarden** [comment]
@piiertho I was able to do some testing on a OS X 10.15 machine and following the installation steps + the signing you mentioned above, the addon is able to be activated as expected. I didn't test further than that as I was able to activate it.

I had a colleague and friend test on a OS X 10.14 machine and he ran into the same errors and issues as I described initially. I'm running OS X 10.13.3, so my assumption is that for whatever reason the library doesn't want to work/doesn't sign properly on anything below OS X 10.15. I'm assuming you're building the library on/for 10.15 - is there a way to target lower versions as well?

**Comment by KieranCarden** [comment]
Update: I compiled everything from source and I was able to get the addon working, so it would appear that the current test release works only for OS X 10.15, whereas I imagine the dylib I compiled is what was needed for the OS version I'm running (10.13.x).

However, I'm now running into the same issue as was posted here: https://github.com/godotengine/godot/issues/38866

For now though this issue can be closed as I've solved the loading of the extension.

**Comment by piiertho** [comment]
Ah yep, this is a Catalina library.
![image](https://user-images.githubusercontent.com/48322356/84360070-d0ea1780-abc9-11ea-8b30-02de0adcf0cf.png)
I'm not sure we will release versions for lower os. It would take a lot of github actions time.
